### ISSUE TITLE
UnboundLocalError: local variable 'experiment_data' referenced before assignment

### ISSUE THREAD

**Issue by sivajyothi1** [IntelAI/unet#11]
Hello, 

When i evaluate the model, i'm facing this issue. Can you please help me  to resolve this issue??

(decathlon) sivajyothi@cougar-U:~/unet/3D$ python evaluate_model.py --data_path /home/sivajyothi/data/Task01_BrainTumour/ --saved_model /home/sivajyothi/unet/3D/saved_model/3d_unet_decathlon.hdf5

Using TensorFlow backend.
Started script on 2019-11-11 00:26:31.874186
OMP: Warning #181: OMP_PROC_BIND: ignored because KMP_AFFINITY has been defined
Loading images and masks from test set
File /home/sivajyothi/data/Task01_BrainTumour/dataset.json doesn't exist. It should be part of the Decathlon directory
Traceback (most recent call last):
  File "evaluate_model.py", line 77, in <module>
    **validation_data_params)
  File "/home/sivajyothi/unet/3D/dataloader.py", line 83, in __init__
    self.list_IDs = self.create_file_list()
  File "/home/sivajyothi/unet/3D/dataloader.py", line 146, in create_file_list
    self.output_channels = experiment_data["labels"]
UnboundLocalError: local variable 'experiment_data' referenced before assignment

Thank you.

**Comment by MasterSkepticista** [comment]
In case someone else still faces this issue, it is because of the wrong path to ```--data_path```
