### ISSUE TITLE
inference_openvino.py low dice score

### ISSUE THREAD

**Issue by malcolmping** [IntelAI/unet#14]
Hi experts,

   after I follow the guidance to train model, I execute 2D inference_openvino.py. However, the result images in "inference_examples_openvino" folder are not correct (no any prediction region) and I'm wondering how can I fix this issue!

Thank you!

Malcolm 

[ INFO ] Loading U-Net model to the plugin
[ INFO ] Loading network files:
	../openvino_models/FP32/saved_model.xml
	../openvino_models/FP32/saved_model.bin
[ INFO ] Loading model to the plugin
[ INFO ] Image #22: Dice score = 1.0000
[ INFO ] Image #40: Dice score = 0.0011
[ INFO ] Image #56: Dice score = 0.0013
[ INFO ] Image #61: Dice score = 0.0029
[ INFO ] Image #400: Dice score = 0.0007
[ INFO ] Image #1100: Dice score = 1.0000
[ INFO ] Image #2229: Dice score = 0.0011
[ INFO ] Image #3136: Dice score = 0.0011
[ INFO ] Image #4385: Dice score = 0.0009
[ INFO ] Could not open font file /usr/share/fonts/truetype/noto/NotoColorEmoji.ttf: In FT2Font: Could not set the fontsize
[ INFO ] generated new fontManager
[ INFO ] Plotting the predictions and saving to png files. Please wait...
Saved file: inference_examples_openvino/pred_group0
Saved file: inference_examples_openvino/pred_group1
Saved file: inference_examples_openvino/pred_group2

![pred_group0](https://user-images.githubusercontent.com/19926622/72525258-b15ef500-389e-11ea-8a91-d4eacf0d7f40.png)

**Comment by tonyreina** [comment]
Did you train the model?  I'm wondering if the results are ok if you run `https://github.com/IntelAI/unet/blob/master/2D/plot_inference_examples.py` with the original TF/Keras version. The OpenVINO version of the TF/Keras model should give you the same results as that.

**Comment by tonyreina** [comment]
Just wanted to check back to see if you were able to train the model? Did the training script report the final Keras/TF model Dice score?
