### ISSUE TITLE
data download from google drive

### ISSUE THREAD

**Issue by jinz2014** [IntelAI/unet#17]
I tried to download the dataset (task 1) from the link provided in the notebook. The links don't seem to work.  May you please update the link so that people can download the large dataset using the command line easily in Linux ?

Thanks

**Comment by shailensobhee** [comment]
Hello, yes the link went down.

Please try the following:

`wget https://raw.githubusercontent.com/shailensobhee/gdown.pl/master/gdown.pl && chmod u+x gdown.pl
./gdown.pl https://drive.google.com/file/d/1A2IU8Sgea1h3fYLpYtFb2v7NYdMjvEhU/view?usp=sharing Task01_BrainTumour.tar`

**Comment by jinz2014** [comment]
Thanks for your update.
