### ISSUE TITLE
hidden file

### ISSUE THREAD

**Issue by wxr521314** [IntelAI/unet#22]
Hello：
I used my own data set, the following error occurred;

FileNotFoundError: No such file or no access: '/home/zhengsc/Desktop/unet/3D/Task100_Colon/./imagesTr/colon_212.nii.gz'

I really don't have this hidden file.
I looked at the contest data and he had a hidden file.
![image](https://user-images.githubusercontent.com/53425125/85941643-9ff23c80-b956-11ea-814c-b4111a158463.png)
How do I generate this hidden file？？

**Comment by ravi9** [comment]
Hi @wxr521314 
Can you verify if you have the file `colon_212.nii.gz'`
Try
`ls -l /home/zhengsc/Desktop/unet/3D/Task100_Colon/./imagesTr/colon_212.nii.gz`
