### ISSUE TITLE
'Model' object has no attribute 'load_model'

### ISSUE THREAD

**Issue by feichai2004** [IntelAI/unet#3]
I tried to run the evaluate_model.py but I faced the following problem.

Data format = channels_last
Traceback (most recent call last):
  File "evaluate_model.py", line 51, in <module>
    model = unet_model.model.load_model(args.saved_model, custom_objects=unet_model.custom_objects)
AttributeError: 'Model' object has no attribute 'load_model'

**Comment by tonyreina** [comment]
Thanks for the report. Please update and try the fix.

**Comment by feichai2004** [comment]
It is working now.
