### ISSUE TITLE
Dice Score

### ISSUE THREAD

**Issue by Haripc525** [IntelAI/unet#32]
I successfully trained the 3d unet model for 30 epochs with a crop size of (64,64,64) and batch size 8 but the dice score was only 0.56. And testing avg dice was 0.4
Could you please help me solving this problem.
And also please explain the usage of openvino.
![gita](https://user-images.githubusercontent.com/55555480/121239725-3a713480-c8b7-11eb-883d-a014934d2884.PNG)

**Comment by tonyreina** [comment]
You should try training for more epochs and possibly using a larger crop (I used 128x128x128) crops. That will yield better Dice.

OpenVINO is a framework for performing inference on Intel hardware that can significantly speedup your inference.
