### ISSUE TITLE
inference_openvino.py: data  type false

### ISSUE THREAD

**Issue by feichai2004** [IntelAI/unet#5]
I tried to run "python inference_openvino.py ",  setting the datapath to dataset.json folder and model input to FP32 folder. I see the following error and no output result is produced. The error is produced by line 67: "validation_generator = DataGenerator(False, args.data_path,
                                         **validation_data_params)"

/usr/lib/python3.5/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
[ INFO ] Loading U-Net model to the plugin
[ INFO ] Loading network files:
        ./FP32/3d_unet_decathlon.xml
        ./FP32/3d_unet_decathlon.bin
[ INFO ] Batch size = 1
error with type of data: False 
[ INFO ] 0 started
[ INFO ] 0 finished
[ INFO ] Partial batch left over in dataset

**Comment by tonyreina** [comment]
I've updated the code to correct this. The only issue I still have is that I haven't had time to confirm the OV output for 3D.

**Comment by feichai2004** [comment]
I noticed that the output dice score is very low. The train set's dice score is 0.85.
[ INFO ] Image #BRATS_457: Dice score = 0.0460
[ INFO ] Image #BRATS_306: Dice score = 0.0196
[ INFO ] Image #BRATS_206: Dice score = 0.0763
[ INFO ] Image #BRATS_449: Dice score = 0.0963
[ INFO ] Image #BRATS_318: Dice score = 0.0418
[ INFO ] Image #BRATS_218: Dice score = 0.0911
[ INFO ] Image #BRATS_434: Dice score = 0.1206
[ INFO ] Image #BRATS_365: Dice score = 0.0358

**Comment by tonyreina** [comment]
Yes. I've got someone looking in that. Hope to provide the fix soon.

**Comment by tonyreina** [comment]
I think I've finally fixed the issue. The OpenVINO model assumes the input dimensions to be batch, channels, depth, height, width.  The Keras/TF model assumes batch, height, width, depth, channels. Can you let me know if the new code works for you?
